# Generated by Django 4.0.1 on 2023-02-02 23:18

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
