# Generated by Django 3.0 on 2022-01-23 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=49)),
                ('rent_price', models.FloatField()),
                ('ondometer', models.FloatField()),
                ('transmition', models.CharField(choices=[('manual', 'manual'), ('auto', 'auto')], max_length=30)),
                ('seats', models.IntegerField()),
                ('fuel', models.CharField(choices=[('petrol', 'petrol'), ('gazoil', 'gazoil')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('luggage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=25)),
                ('dropoff_location', models.CharField(max_length=25)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule')),
            ],
        ),
    ]
