# Generated by Django 3.0 on 2022-01-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0003_auto_20220124_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pickup_time',
        ),
    ]
