# Generated by Django 3.0 on 2022-01-24 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0004_remove_location_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
