# Generated by Django 3.0 on 2022-01-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0005_auto_20220124_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
